Repository CS2103JAN2018-W14-B4/main, pull requests merged in 2018-04, with the labels that each got.

#117 New UI
  src/main/resources/view/DarkTheme.css
Labels: component.ui, severity.low

#116 Fix bug for appt not showing in calendar
  src/main/java/seedu/address/commons/events/ui/ChangeCalendarRequestEvent.java
  src/main/java/seedu/address/logic/commands/calendar/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/ViewCalendarCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CalendarPanel.java
Labels: component.logic, type.bug

#119 Add support for celebrity in different commands
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/person/Celebrity.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: component.model, type.bug

#120 Edit appointment command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/calendar/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/ViewAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/calendar/EditAppointmentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: severity.high, type.enhancement, type.story

#121 Add celebrities to address book for testing
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/calendar/ViewCalendarByCommand.java
  src/main/java/seedu/address/logic/map/DistanceEstimate.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/calendar/StorageCalendar.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveTagCommandTest.java
  src/test/java/seedu/address/logic/parser/RemoveTagCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/TypicalCelebrities.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: component.model, component.storage, type.testing

#122 completed editAppointment Command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/calendar/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/calendar/EditAppointmentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: severity.high, type.documentation, type.story

#123 update View appointment
  src/main/java/seedu/address/logic/commands/calendar/ViewAppointmentCommand.java
  src/main/java/seedu/address/logic/map/DistanceEstimate.java
  src/main/java/seedu/address/logic/map/Geocoding.java
  src/main/java/seedu/address/logic/parser/calendar/ViewAppointmentCommandParser.java
Labels: component.logic, type.bug

#127 Update UG
  docs/UserGuide.adoc
  docs/images/ViewCalendarByDay.jpg
  docs/images/ViewCalendarByMonth.jpg
  docs/images/ViewCalendarByWeek.jpg
Labels: type.documentation

#130 Create viewDate feature
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/ShowCalendarBasedOnDateEvent.java
  src/main/java/seedu/address/logic/commands/calendar/ViewDateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/calendar/ViewDateCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: component.ui, type.documentation, type.enhancement, type.task

#136 Give person id
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/calendar/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/ListAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/calendar/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/calendar/EditAppointmentCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/person/Celebrity.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/XmlAdaptedAppointment.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/resources/view/AppointmentListCard.fxml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/calendar/AddAppointmentCommandParserTest.java
Labels: severity.high, type.epic

#137 update map related features
  src/main/java/seedu/address/logic/commands/calendar/ViewAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/calendar/ViewAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/map/EstimateRouteCommandParser.java
  src/main/java/seedu/address/logic/parser/map/ShowLocationCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
Labels: component.logic, type.bug

#139 Update UG
  docs/UserGuide.adoc
Labels: type.documentation

#142 Change viewDate feature's input format...
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/calendar/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/ViewAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/ViewDateCommand.java
  src/main/java/seedu/address/logic/parser/calendar/DeleteAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/calendar/ViewDateCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/calendar/DeleteAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/calendar/ViewDateCommandParserTest.java
Labels: component.logic, type.task, type.testing

#149 Extend functionality of listAppointment
  src/main/java/seedu/address/logic/commands/calendar/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/ListAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/ViewDateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/calendar/ListAppointmentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/calendar/ListAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/calendar/ViewDateCommandParserTest.java
Labels: component.logic, type.task, type.testing

#150 Create test for DeleteAppointmentCommand
  src/main/java/seedu/address/logic/commands/calendar/DeleteAppointmentCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/calendar/DeleteAppointmentCommandTest.java
Labels: component.logic, type.testing

#155 added GoogleWebService class
  src/main/java/seedu/address/logic/map/DistanceEstimate.java
  src/main/java/seedu/address/logic/map/Geocoding.java
  src/main/java/seedu/address/logic/map/GoogleWebServices.java
  src/main/java/seedu/address/logic/parser/map/EstimateRouteCommandParser.java
  src/main/java/seedu/address/logic/parser/map/ShowLocationCommandParser.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/BrightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/ui/testutil/UiPartRule.java
Labels: component.logic, type.bug

#166 Create test
  src/main/java/seedu/address/logic/commands/calendar/ViewCalendarCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/calendar/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/calendar/ViewCalendarByCommandTest.java
  src/test/java/seedu/address/logic/commands/calendar/ViewCalendarCommandTest.java
  src/test/java/seedu/address/logic/commands/calendar/ViewCombinedCalenrCommandTest.java
  src/test/java/seedu/address/logic/commands/calendar/ViewDateCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: component.logic, type.testing

#170 Map related test update
  src/main/java/seedu/address/logic/commands/map/EstimateRouteCommand.java
  src/main/java/seedu/address/logic/commands/map/ShowLocationCommand.java
  src/test/java/seedu/address/logic/commands/map/EstimateRouteCommandTest.java
  src/test/java/seedu/address/logic/commands/map/ShowLocationCommandTest.java
  src/test/java/systemtests/calendar/ViewAppointmentCommandSystemTest.java
Labels: component.logic, type.testing

#174 Added project portfolio
  docs/team/Muruges.adoc
Labels: type.documentation

#175 Update UG and project portfolio
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/WJY-norainu.adoc
Labels: type.documentation

#176 Update DG and PPP
  docs/DeveloperGuide.adoc
  docs/diagrams/ReadStorageSequenceDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/WriteStorageSequenceDiagram.pptx
  docs/images/ReadStorageCalendarSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/team/tzerbin.adoc
Labels: type.documentation

#178 Remove change of calendar when selecting celebrity
  src/main/java/seedu/address/commons/events/ui/PersonPanelSelectionChangedToCelebrityEvent.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/systemtests/RemoveTagCommandSystemTest.java
Labels: component.logic, type.testing

#181 Included system test for add appointment command
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/calendar/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/calendar/AddAppointmentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/calendar/StorageCalendar.java
  src/main/java/seedu/address/model/person/Celebrity.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateAppointmentException.java
  src/main/java/seedu/address/storage/XmlSerializableStorageCalendar.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/commands/calendar/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/calendar/EditAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/calendar/ViewAppointmentCommandTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/AppointmentUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalStorageCalendar.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/SystemTestSetupHelper.java
  src/test/java/systemtests/calendar/AddAppointmentCommandSystemTest.java
Labels: severity.medium, type.testing

#186 Add appointment command system tests
  .gitignore
  config.json
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/calendar/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/map/GoogleWebServices.java
  src/main/java/seedu/address/logic/parser/calendar/AddAppointmentCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/calendar/StorageCalendar.java
  src/main/java/seedu/address/model/person/Celebrity.java
  src/main/java/seedu/address/storage/XmlAdaptedAppointment.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/AppointmentListWindow.fxml
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MapsPanel.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/map/EstimateRouteCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/AppointmentUtil.java
  src/test/java/systemtests/calendar/AddAppointmentCommandSystemTest.java
  src/test/resources/view/UiPartTest/validFileWithFxRoot.fxml
Labels: type.enhancement

#195 Annotations for collating code
  docs/team/Damienskt.adoc
  src/main/resources/view/BrightTheme.css
  src/test/java/seedu/address/logic/commands/calendar/ViewAppointmentCommandTest.java
Labels: type.documentation

#197 Documentation update
  docs/DeveloperGuide.adoc
  docs/images/ModelClassDiagram.jpg
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/logic/map/GoogleWebServices.java
Labels: type.documentation
