Repository CS2103JAN2018-W14-B4/main, pull requests merged in 2018-03, with the labels that each got.

#17 Added basic Calendar
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/calendar/AddAppointmentCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: UI, enhancement, model

#32 Edited setting up section in DG
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
Labels: Documentation

#45 Create add appointment parser test
  src/main/java/seedu/address/logic/commands/calendar/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/calendar/AddAppointmentCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/calendar/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
Labels: Logic, testing

#51 Revised add appointment command and added feature contribution
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/calendar/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/calendar/AddAppointmentCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/test/java/guitests/GuiRobot.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/calendar/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
Labels: Documentation

#52 fixed a bug in addAppointment
  src/main/java/seedu/address/logic/parser/calendar/AddAppointmentCommandParser.java
  src/test/java/seedu/address/logic/parser/calendar/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
Labels: Logic, bug

#58 Updated developer and user guide for showLocation command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ShowLocationLogicComponentCommandClassDiagram.pptx
  docs/diagrams/ShowLocationSequenceDiagram.pptx
  docs/images/AfterShowLocationInput.png
  docs/images/BeforeInput.png
  docs/images/LocationMarker.png
  docs/images/ShowLocationLogicCommandClassDiagram.png
  docs/images/ShowLocationSequenceDiagram.png
Labels: Documentation

#54 added Show location command and test
  src/main/java/seedu/address/logic/commands/map/ShowLocationCommand.java
  src/main/java/seedu/address/logic/map/DistanceEstimate.java
  src/main/java/seedu/address/logic/map/Geocoding.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/map/ShowLocationCommandParser.java
  src/main/java/seedu/address/model/map/MapAddress.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/ui/MapPanel.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ShowLocationCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ShowLocationCommandParserTest.java
  src/test/java/seedu/address/model/map/MapAddressTest.java
  src/test/java/systemtests/ShowLocationCommandSystemTest.java
Labels: Logic, enhancement, model

#53 Modification to Storage Component to support Appointment
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/appointment/AppointmentList.java
  src/main/java/seedu/address/model/appointment/ReadOnlyAppointmentList.java
  src/main/java/seedu/address/storage/AppointmentListStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAdaptedAppointment.java
  src/main/java/seedu/address/storage/XmlAppointmentListStorage.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/main/java/seedu/address/storage/XmlSerializableAppointmentList.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: Storage, bug, enhancement

#59 Added implementation in DG
  docs/DeveloperGuide.adoc
  docs/images/AfterAddAppointment.png
  docs/images/BeforeAddAppointment.png
Labels: Documentation

#60 Update Developer Guide with AppointmentStorage feature
  docs/DeveloperGuide.adoc
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/StorageClassDiagram.png
Labels: Documentation

#61 Update Developer Guide for removeTag Command
  docs/DeveloperGuide.adoc
  docs/diagrams/RemoveTagSequenceDiagram.pptx
  docs/images/AfterRemoveTag.png
  docs/images/BeforeRemoveTag.png
  docs/images/RemoveTagSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/test/java/systemtests/RemoveTagCommandSystemTest.java
Labels: Documentation

#64 Change implementation of removeTag
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/exceptions/TagNotFoundException.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/systemtests/RemoveTagCommandSystemTest.java
Labels: type.epic

#78 Added ability to add celebrities into the program
  src/main/java/seedu/address/logic/commands/calendar/AddAppointmentCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/calendar/CelebCalendar.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: component.logic, component.model

#88 Implement viewCalendarBy feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/ui/ChangeCalendarViewPageRequestEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/ViewCalendarByCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCalendarByCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/CalendarPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: component.logic, component.ui, type.task

#93 Updated UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.documentation

#98 Implement viewCalendarBy feature and update DG
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/ui/ChangeCalendarViewPageRequestEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/ViewCalendarByCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCalendarByCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/CalendarPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: component.ui, type.documentation, type.task

#99 Update DG
  docs/DeveloperGuide.adoc
Labels: type.documentation

#101 Updated Documentation in DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: type.bug, type.documentation

#102 Estimate route feature and test
  src/main/java/seedu/address/logic/commands/map/EstimateRouteCommand.java
  src/main/java/seedu/address/logic/commands/map/ShowLocationCommand.java
  src/main/java/seedu/address/logic/map/DistanceEstimate.java
  src/main/java/seedu/address/logic/map/Geocoding.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/map/EstimateRouteCommandParser.java
  src/main/java/seedu/address/logic/parser/map/ShowLocationCommandParser.java
  src/main/java/seedu/address/model/map/MapAddress.java
  src/main/java/seedu/address/ui/MapPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MapsPanel.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/test/java/seedu/address/logic/commands/map/EstimateRouteCommandTest.java
  src/test/java/seedu/address/logic/commands/map/ShowLocationCommandTest.java
  src/test/java/seedu/address/logic/parser/map/EstimateRouteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/map/ShowLocationCommandParserTest.java
  src/test/java/systemtests/map/EstimateRouteCommandSystemTest.java
  src/test/java/systemtests/map/ShowLocationCommandSystemTest.java
Labels: severity.medium, type.task, type.testing

#97 Edit Section 4 Implementation of DG
  docs/DeveloperGuide.adoc
Labels: type.documentation

#104 Update UG for v1.3 release
  docs/UserGuide.adoc
Labels: type.documentation

#103 Standardise DG
  docs/DeveloperGuide.adoc
Labels: type.documentation

#105 Associate celebrities
  docs/UserGuide.adoc
  docs/team/johndoe.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/calendar/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/calendar/AddAppointmentCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/parser/calendar/AddAppointmentCommandParserTest.java
Labels: component.logic, component.ui, severity.high, type.story

#107 .docx version of UG and DG
  docs/DeveloperGuide.adoc
  docs/docx/CelebManager_DeveloperGuide.docx
  docs/docx/CelebManager_UserGuide.docx
Labels: type.documentation

#108 Updated UGDG with EstimateRoute features
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/EstimateRouteSequenceDiagram.pptx
  docs/diagrams/ShowLocationSequenceDiagram.pptx
  docs/images/AfterEstimateRouteInput.png
  docs/images/BeforeInput.png
  docs/images/BeforeInputMap.png
  docs/images/EstimateRouteSequenceDiagram.png
  docs/images/ShowLocationSequenceDiagram.png
Labels: type.documentation

#110 added MapAddress property for each appointment
  src/main/java/seedu/address/logic/parser/calendar/AddAppointmentCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/calendar/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
Labels: component.model, severity.medium, type.task, type.testing

#109 Implement ViewCalendar and ViewCombinedCalendar
  src/main/java/seedu/address/commons/events/ui/ChangeCalendarRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/PersonPanelSelectionChangedToCelebrityEvent.java
  src/main/java/seedu/address/commons/events/ui/ShowCombinedCalendarViewRequestEvent.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/calendar/ViewCalendarByCommand.java
  src/main/java/seedu/address/logic/commands/calendar/ViewCalendarCommand.java
  src/main/java/seedu/address/logic/commands/calendar/ViewCombinedCalendarCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/calendar/ViewCalendarByCommandParser.java
  src/main/java/seedu/address/logic/parser/calendar/ViewCalendarCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/CalendarPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: component.ui, type.task

#112 Replace legal values for view page to static variables
  src/main/java/seedu/address/logic/commands/calendar/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/ListAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/ViewCalendarByCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CalendarPanel.java
Labels: component.model, type.task

#113 Change map API key
  src/main/java/seedu/address/logic/commands/calendar/ListAppointmentCommand.java
  src/main/java/seedu/address/logic/map/DistanceEstimate.java
  src/main/java/seedu/address/logic/map/Geocoding.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CalendarPanel.java
Labels: type.bug

#114 update Estimate route feature
  build.gradle
  src/main/java/seedu/address/logic/commands/map/EstimateRouteCommand.java
  src/main/java/seedu/address/logic/commands/map/ShowLocationCommand.java
  src/main/java/seedu/address/logic/map/DistanceEstimate.java
  src/main/java/seedu/address/logic/map/Geocoding.java
  src/main/java/seedu/address/model/map/Map.java
  src/main/java/seedu/address/ui/MapPanel.java
  src/test/java/seedu/address/logic/commands/map/EstimateRouteCommandTest.java
  src/test/java/seedu/address/logic/commands/map/ShowLocationCommandTest.java
  src/test/java/seedu/address/logic/map/DistanceEstimateTest.java
  src/test/java/seedu/address/logic/map/GeocodingTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/map/MapAddressTest.java
  src/test/java/systemtests/map/EstimateRouteCommandSystemTest.java
  src/test/java/systemtests/map/ShowLocationCommandSystemTest.java
Labels: component.ui, severity.medium, type.enhancement

#115 Implement deleteAppointment feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/ui/ShowCalendarEvent.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/calendar/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/ListAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/calendar/ViewCalendarByCommand.java
  src/main/java/seedu/address/logic/commands/calendar/ViewCalendarCommand.java
  src/main/java/seedu/address/logic/commands/calendar/ViewCombinedCalendarCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/calendar/DeleteAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/calendar/ViewCalendarCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/AppointmentListWindow.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/AppointmentListWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: component.logic, type.task
